webtalk_init -webtalk_dir /home/cdespaux/Bureau/ProjetSysInfo/Projet/Microprocesseur/Microprocesseur.sim/sim_1/behav/xsim/xsim.dir/test_banc_registres_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue May 30 10:56:26 2023" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "be04f8de5c105e4e9add994841e5fb3a" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2fc3e043c9224ad5bb854cbd6babc667" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 20.04.6 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3200.000 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "67.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "3" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.03_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "118504_KB" -context "xsim\\usage"
webtalk_transmit -clientid 103726382 -regid "" -xml /home/cdespaux/Bureau/ProjetSysInfo/Projet/Microprocesseur/Microprocesseur.sim/sim_1/behav/xsim/xsim.dir/test_banc_registres_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/cdespaux/Bureau/ProjetSysInfo/Projet/Microprocesseur/Microprocesseur.sim/sim_1/behav/xsim/xsim.dir/test_banc_registres_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/cdespaux/Bureau/ProjetSysInfo/Projet/Microprocesseur/Microprocesseur.sim/sim_1/behav/xsim/xsim.dir/test_banc_registres_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
